# Generated by Django 4.1 on 2022-09-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_alter_todo_date_ticked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="date_ticked",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
