# Generated by Django 4.1 on 2022-09-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_todo_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="data_created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
