# Generated by Django 4.1 on 2022-09-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_todo_data_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
    ]
